name: holly-stream

networks:
  backend:
    driver: bridge
  global-nginx:
    external: true
  triton:
    driver: bridge

services:
  app:
    container_name: holly-stream-app
    image: rcland12/detection-stream:linux-latest
    build:
      context: ./app
    group_add:
      - audio
    networks:
      - backend
      - global-nginx
      - triton
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/argus_socket:/tmp/argus_socket
      - ./triton:/root/app/triton
    env_file: .env

  triton:
    container_name: holly-stream-triton
    image: rcland12/detection-stream:linux-triton-latest
    build:
      context: ./triton
    networks:
      - triton
    ports:
      - 8000:8000
      - 8001:8001
    shm_size: 512mb
    volumes:
      - ./triton:/models
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-i",
          "-X",
          "GET",
          "http://localhost:8000/v2/health/ready",
        ]
      interval: 5s
      timeout: 10s
      retries: 6

  nginx-stream:
    container_name: holly-stream-nginx-stream
    image: rcland12/detection-stream:nginx-latest
    build:
      context: ./nginx
    networks:
      - backend
    ports:
      - ${STREAM_PORT}:${STREAM_PORT}
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && kill -0 $(cat /tmp/nginx.pid)"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 10s

  nginx-web:
    container_name: holly-stream-nginx-web
    image: rcland12/detection-stream:nginx-latest
    build:
      context: ./nginx
    networks:
      - backend
    ports:
      - 8088:8080
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && kill -0 $(cat /tmp/nginx.pid)"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 10s
