FROM debian:stable-slim
ARG APPDIR="/root/app"

WORKDIR ${APPDIR}
COPY linux.py model.py utilities.py ./

ARG OPENCV_VERSION=3.4.18.65

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    pip3 install ultralytics supervision && \
    pip3 uninstall -y opencv-python && \
    pip3 install opencv-python-headless==${OPENCV_VERSION}

CMD ["python3", "linux.py"]
