services:
  triton:
    image: rcland12/detection-stream:linux-triton-latest
    build:
      context: ./triton
    network_mode: host
    shm_size: 128mb
    volumes:
      - ./triton:/root/app/triton
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: [ "CMD", "curl", "-i", "-X", "GET", "http://localhost:8000/v2/health/ready" ]
      interval: 10s
      timeout: 20s
      retries: 6

  app:
    image: rcland12/detection-stream:linux-latest
    build:
      context: ./app
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/argus_socket:/tmp/argus_socket
      - ./triton:/root/app/triton
    env_file: .env
    restart: unless-stopped

  nginx-stream:
    image: rcland12/detection-stream:nginx-latest
    build:
      context: ./nginx
    network_mode: host
    volumes:
      - ${PWD}/nginx/nginx-stream/nginx.conf:/etc/nginx/nginx.conf

  nginx-web:
    image: rcland12/detection-stream:nginx-latest
    build:
      context: ./nginx
    network_mode: host
    volumes:
      - ${PWD}/nginx/nginx-web/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/stream:/var/www/html/stream
