name: "yolo11"
platform: "ensemble"
max_batch_size: 8

input [
  {
    name: "image"
    data_type: TYPE_UINT8
    dims: [ 720, 1280, 3 ]
  }
]

output [
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [ -1, 6 ]
    label_filename: "labels.txt"
  },
  {
    name: "num_dets"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "preprocess"
      model_version: -1
      input_map {
        key: "image"
        value: "image"
      }
      output_map {
        key: "resized_image"
        value: "resized_image"
      }
    },
    {
      model_name: "object_detection"
      model_version: -1
      input_map {
        key: "images"
        value: "resized_image"
      }
      output_map {
        key: "output0"
        value: "detections"
      }
    },
    {
      model_name: "postprocess"
      model_version: -1
      input_map {
        key: "detections"
        value: "detections"
      }
      output_map {
        key: "boxes"
        value: "boxes"
      }
      output_map {
        key: "num_dets"
        value: "num_dets"
      }
    }
  ]
}

version_policy: { 
  latest: { num_versions: 1 }
}
