name: "postprocess"
backend: "python"
max_batch_size: 0

input [
  {
    name: "INPUT_0"
    data_type: TYPE_FP16
    dims: [ -1, -1, -1 ]
  }
]

output [
  {
    name: "OUTPUT_0"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]

model_warmup [
  {
    name : "postprocess model warmup"
    batch_size: 1
    inputs {
      key: "INPUT_0"
      value: {
          data_type: TYPE_FP16
          dims: [ 1, 25200, 85 ]
          input_data_file: "INPUT_0"
      }
    }
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]

version_policy: { 
  latest: { num_versions: 1 }
}

response_cache { 
  enable: True
}